[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
